### PR TITLE
Requesting for ontop-spatial plugin for protege

### PR DESCRIPTION
**Pull request by dras130**
Dear sir,

We are working in R&D projects sponsored by Govt. of India. We would like congratulate for developing effective tools such as ontop-spatial. In the past we have experience with ontop it really helped us. Now we would like to use ontop-spatial in our project to execute semantic queries (GeoSPARQL) on Geo-spatial data. 

Is there ontop-spatial plugin for protege like ontop? if yes, kindly provide the link for us.

Please help us to proceed further. 

Thanks & Regards
Dr. Sunitha Abburu & Research Team

### CODE REVIEW

**Comment by ghxiao** [comment]
Dear @dras130. Thanks for your request.

@ConstantB It seems that the issue system is not enabled in your fork https://github.com/ConstantB/ontop-spatial. That's why the discussion happens here.

As far as I remember, there were some packing issues with the protege plugin. We can work together to fix it.  It is also my interest.

@dras130 Please note that we will not merge this pull request. The development of ontop-spatial has to be kept in its own repository/fork for technical reasons. More specifically, ontop-spatial currently relies on a customized version of sesame library v2 for parsing Geo-SPARQL queries. In the future, once we upgrade sesame to v4, where Geo-SPARQL queries are supported natively, we can work on merging the fork back to the main repository.

Btw, we are collecting use cases of ontop for writing proposals to keep the development of ontop. I would be very grateful if you can drop a few lines on
https://github.com/ontop/ontop/wiki/UseCases

**Comment by dras130** [comment]
Dear Sir,

Our use case is: Mapping 2D and 3D geometries stored in postgreSQL to any
domain ontology and execute GeoSPARQL using R2RML/ontop mappings.

Please provide any link or document that guide us to proceed further in
these lines.

We have generated R2RML mappings using GeoTriples. Kindly share the
procedure/java library/code to execute GeoSPARQL query on the spatial
database using R2RML mappings.

Thanks & Regards
Research Team.

**Comment by ConstantB** [comment]
Dear @dras130, 

thank you for your request and your interest in our work. I apologize for the very late reply, I was very busy these days. 

As @ghxiao mentioned, ontop-spatial cannot be used as a Protege plugin. I plan to do this in the near future. 

I created a repository that contains an example (Database dump, mappings) and a pre-compiled instance of ontop-spatial: https://github.com/ConstantB/Ontop-spatial-example, as well as this wiki page that explains its use: https://github.com/ConstantB/Ontop-spatial-example/wiki. 

I strongly recommend that you use it as a web application (just drop the .war files into a web server installation, e.g., the webapps folder of an apache tomcat installation and use it from the sesame workbench endpoint as the default version of ontop. 

Supporting 3D geometries are not tested, as we have focused on 2D geometries so far, however, as it is the first use case that deals with 3D geometries I am very interested to help with it. 

For any further guidance and/support, please contact me at const.di at gmail.com 

Kind Regards, 
Konstantina

**Comment by ConstantB** [comment]
@dras130 In addition to the above, for testing purposes it might also be convinient to import the source code of ontop-spatial into your IDE (eclipse, netbeans, etc.) as a maven project and then create a test class like this example here that demonstrates the use of ontop-spatial via the Sesame API: 

https://github.com/ConstantB/ontop-spatial/blob/master/quest-sesame/src/test/java/inf/unibz/ontop/sesame/tests/general/SesameLGDTest.java

Kind Regards, 
Konstantina

**Comment by ConstantB** [comment]
I justed reported the issue here: https://github.com/ConstantB/ontop-spatial/issues/1

**Comment by ghxiao** [comment]
The discussion will be moved to ConstantB#1

**Comment by dras130** [comment]
Sir,

Could you please provide SF and EH function syntax for GeoSPARQL.

Thanks & Regards
Research Team

**Comment by ghxiao** [comment]
@dras130 Let's continue our discussion at ConstantB#1

PS: @ConstantB has informed me that she has achieved significant progress in protege plugin.

**Pull request closed without merging**
