### PR TITLE
Fix RDB2RDF compliance tests

### PR DESCRIPTION
**Pull request by evren**
Tests were never checking expected outputs and instead clearing expected output files
Update unit dependency to 4.11 (to use parameterized tests)
Upgrade RDB2RDF tests JUnit3 to JUnit4
Use a simpler mechanism to create parameterized tests without a repository
Speed up tests by avoiding db reload when test use the same dataset
Create an ignore list for 50 failing test cases

### CODE REVIEW

**Comment by ghxiao** [comment]
@evren Thanks very much for your PR and I believe this is a great start!

In order to merge your changes, we will need a Contribution License Agreement (CLA) that allows FUB and the ontop team to redistribute your work under the terms of the Apache 2.0 license.

Could you check the CLAs, sign them and send the scans to me?

http://ontop.inf.unibz.it/license/

**Comment by ghxiao** [comment]
@evren Did you have time to check this?

**Comment by evren** [comment]
I'm updating this pull request to include some bug fixes for 25 failures.

**Comment by marianormuro** [comment]
thanks evren, i was about to start the merge, good timing :)


On Tue, Nov 3, 2015 at 4:55 PM, Evren Sirin <notifications@github.com>
wrote:

> I'm updating this pull request to include some bug fixes for 25 failures.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ontop/ontop/pull/67#issuecomment-153501787>.
>



-- 

Mariano Rodriguez Muro
http://www.rodriguez-muro.com
https://w3-connections.ibm.com/profiles/html/profileView.do?uid=3G3860897

Research Staff, IBM Research
IBM T.J. Watson research center
Yorktown heights, NY. USA
+1-914-945-2607

home: mariano.muro@gmail.com
work: mrodrig@us.ibm.com

**Comment by ghxiao** [comment]
@evren I have merged your PR. Indeed the test framework is much faster than before. However I also had a feeling that the framework is somehow sensitive to the concrete syntax of the RDF graph. For instance, if the labels of BNodes in the expected and actual graphs do not match, then the test framework treat them as different and fail the test case.

**Comment by ghxiao** [comment]
@evren Actually you are right. I thought that dg0018 fails because of BNode labels. I had a closer look and the unmatched part is actually about the spaces in literals "Venus          " and "Venus".

**Pull request merged**
